version: "3.7"

services:
  # Device API Handler
  device_api_handler:
    build:
      context: ./bin/device-api-handler
    image: sashuu6/weather_station_cluster_frontend:device_api
    container_name: "device_api-weather_station_cluster_frontend-sashuu6"
    restart: "always"
    ports:
      - "${API_DEVICE_PORT}:5000"
    volumes:
      - ${LOG_FILE-./logs/device_api_handler/}:/var/log/device_api_handler/

  # Public API Handler
  public_api_handler:
    build:
      context: ./bin/public-api-handler
    image: sashuu6/weather_station_cluster_frontend:public_api
    container_name: "public_api-weather_station_cluster_frontend-sashuu6"
    restart: "always"
    ports:
      - "${PUBLIC_DEVICE_PORT}:5000"
    volumes:
      - ${LOG_FILE-./logs/public_api_handler/}:/var/log/public_api_handler/
