version: "3.7"

services:
  # MongoDB
  mongodb:
    build:
      context: ./bin/mongodb
    image: sashuu6/home_weather_station_mini_datacenter:mongodb
    container_name: "mongodb-home_weather_station_mini_datacenter-sashuu6"
    restart: "always"
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${MONGODB_DATA_DIR-./data/mongodb}:/data/db
      - ${MONGODB_CONFIG_DIR-./config/mongodb/mongod.conf}:/etc/mongo/mongod.conf
      - ${MONGODB_LOG_DIR-./logs/mongodb/}:/var/log/mongodb/
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    command: --config /etc/mongo/mongod.conf

  # Mongo Express
  mongo-express:
    build:
      context: ./bin/mongo-express
    image: sashuu6/home_weather_station_mini_datacenter:mongo-express
    container_name: "mongo_express-home_weather_station_mini_datacenter-sashuu6"
    restart: always
    ports:
      - "${MONGOEXPRESS_PORT}:8081"
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}

  # MySQL
  mysql:
    build:
      context: ./bin/mysql
    image: sashuu6/home_weather_station_mini_datacenter:mariadb
    container_name: "mariadb-home_weather_station_mini_datacenter-sashuu6"
    restart: "always"
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      TZ: ${TimeZone}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  # PHPMyAdmin
  phpmyadmin:
    build:
      context: ./bin/phpmyadmin
    image: sashuu6/home_weather_station_mini_datacenter:phpmyadmin
    container_name: "phpmyadmin-home_weather_station_mini_datacenter-sashuu6"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: ${HOST_MACHINE_MYSQL_PORT}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - /sessions
